[project]
name = "rl_experiments"
version = "1.0"
description = "Trying out RL algorithms..."
authors = [
    {name = "Ahmed Troudi", email = "ahmed.troudi.fst@gmail.com"},
]
dependencies = [
    "numpy>=1.26.2",
]
requires-python = ">=3.10"
readme = "README.md"
license = {text = "MIT"}

